server:
  port: 19100
spring:
  application:
    name: spring-boot-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.128.106.122:3306/tsw_demo?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
